//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRepairShopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOfModel
    {
        public int SE_ID { get; set; }
        public int T_ID { get; set; }
        public decimal COST { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual TypeOfCar TypeOfCar { get; set; }
    }
}
